function schema = phase3FeatureSchema()
%phase3FeatureSchema The locked Phase 3 dataset column set.
%
%   SCHEMA = phase3FeatureSchema() returns the ordered column names for the
%   labelled feature CSV.
%
%   extractWindowedFeatures and writeFeatureCSV both assert against this
%   list. Changing it invalidates every CSV already generated.

    schema = { ...
        'scenario', ...              % UMa | RMa | UMi
        'seed', ...                  % run RNG seed
        'ueID', ...                  % simulator node ID
        'label', ...                 % 0 terrestrial, 1 aerial (ground truth)
        'winStart_s', ...
        'winEnd_s', ...
        'servSINR_mean_dB', ...
        'servSINR_var_dB2', ...
        'nbrSINR_max_mean_dB', ...
        'nbrSINR_mean_mean_dB', ...
        'sinrSpread_mean_dB', ...
        'numAboveThr_mean', ...
        'hoCount_win', ...
        'meanInterHO_s'};
end
