function schema = phase3FeatureSchema()
%phase3FeatureSchema The locked Phase 3 dataset column set.
%
%   SCHEMA = phase3FeatureSchema() returns the ordered column names for the
%   labelled feature CSV.
%
%   This list is final for every later phase, and changing it invalidates
%   every CSV already generated, so it is the single source of truth that
%   extractWindowedFeatures and writeFeatureCSV both assert against.
%
%   The scenario column is in the schema so all three forks emit identical
%   column sets and their CSVs concatenate without rework.

    schema = { ...
        'scenario', ...              % UMa | RMa | UMi
        'seed', ...                  % run RNG seed
        'ueID', ...                  % simulator node ID
        'label', ...                 % 0 terrestrial, 1 aerial (ground truth)
        'winStart_s', ...
        'winEnd_s', ...
        'servSINR_mean_dB', ...
        'servSINR_var_dB2', ...
        'nbrSINR_max_mean_dB', ...
        'nbrSINR_mean_mean_dB', ...
        'sinrSpread_mean_dB', ...
        'numAboveThr_mean', ...
        'hoCount_win', ...
        'meanInterHO_s'};
end
