function schema = phase3FeatureSchema()
% returns the ordered column names for the Phase 3 labelled feature CSV.
% single source of truth, so every writer and reader asserts against it.

    schema = { ...
        'scenario', ...              % UMa, RMa, UMi
        'seed', ...                  % run seed
        'ueID', ...                  % node id
        'label', ...                 % 0 terrestrial, 1 aerial
        'winStart_s', ...
        'winEnd_s', ...
        'servSINR_mean_dB', ...
        'servSINR_var_dB2', ...
        'nbrSINR_max_mean_dB', ...
        'nbrSINR_mean_mean_dB', ...
        'sinrSpread_mean_dB', ...
        'numAboveThr_mean', ...
        'hoCount_win', ...
        'meanInterHO_s'};
end
