function schema = phase4FeatureSchema()
% returns the ordered column names for the Phase 4 labelled feature CSV.
% the Phase 3 schema is kept as an exact prefix and new columns appended.

    schema = [phase3FeatureSchema(), { ...
        'cqi_mean', ...
        'cqi_var', ...
        'cqi_trend_perS', ...
        'mcsDL_mean', ...
        'mcsDL_var', ...
        'mcsUL_mean', ...
        'mcsUL_var', ...
        'ulVol_bytes', ...
        'dlVol_bytes', ...
        'dlulAsym', ...
        'trafficBurstiness_cv', ...
        'thr_mean_bps'}];
end
