function schema = phase5FeatureSchema()
% returns the ordered column names for the Phase 5 labelled feature CSV.
% the Phase 4 schema is kept as an exact prefix and new columns appended.

    schema = [phase4FeatureSchema(), { ...
        ... % rank and CSI structure
        'ri_mean', ...
        'ri_var', ...
        'rankOne_frac', ...
        'cqiSubbandSpread_mean', ...
        'ulMcsCtx_mean', ...
        'ulMcsCtx_var', ...
        ... % resource consumption
        'prbDL_mean', ...
        'prbUL_mean', ...
        'prbDL_sum', ...
        'prbUL_sum', ...
        'grantRateDL_perS', ...
        'grantRateUL_perS', ...
        'layers_mean', ...
        'spectralEff_bpsPerPRB', ...
        ... % reliability
        'retxRateDL', ...
        'retxRateUL', ...
        'retxRate', ...
        ... % timing advance
        'ta_mean', ...
        'ta_var', ...
        'ta_trend_perS', ...
        'ta_range', ...
        ... % serving SINR dynamics
        'servSINR_trend_perS', ...
        'servSINR_range_dB', ...
        'servSINR_iqr_dB', ...
        'servSINR_min_dB', ...
        'servSINR_max_dB', ...
        'servSINR_autocorr1', ...
        'servSINR_fadeRate_dBperS', ...
        ... % cell geometry
        'servMinusBestNbr_mean_dB', ...
        'servMinusBestNbr_min_dB', ...
        'nbrSINR_max_var_dB2', ...
        'sinrSpread_var_dB2', ...
        'sinrSpread_trend_perS', ...
        'numAboveThr_var', ...
        'numAboveThr_max', ...
        'numAboveThr_trend_perS', ...
        'nbrWithin3dB_mean', ...
        'nbrWithin6dB_mean', ...
        'top3NbrSpread_mean_dB', ...
        ... % serving-cell history
        'distinctServCells_win', ...
        'servCellEntropy', ...
        'pingPongCount_win', ...
        'hoRate_perS', ...
        'timeSinceHO_mean_s', ...
        'timeSinceHO_min_s', ...
        ... % traffic
        'ulThr_bps', ...
        'dlThr_bps', ...
        'trafficIdle_frac', ...
        'ulVol_trend_Bps', ...
        'dlVol_trend_Bps'}];
end
