function map = phase5_ResolveRNTI(cfg, gNBs, UEs, anchorIdx, printMap)
% resolves both RNTI conventions for every UE before a run and validates the
% scheduler mapping against the toolbox connection tables.

    if nargin < 5 || isempty(printMap), printMap = true; end

    numUE = numel(UEs);
    map = struct();
    map.sched   = zeros(1, numUE);
    map.srs     = [UEs.ID] + cfg.rntiOffset;
    map.ueID    = [UEs.ID];
    map.anchor  = anchorIdx;
    map.offset  = cfg.rntiOffset;

    for u = 1:numUE
        g = gNBs(anchorIdx(u));
        assert(isprop(g, 'UENodeIDs') && isprop(g, 'ConnectedUEs'), ...
            'phase5_ResolveRNTI:noConnectionTable', ...
            ['nrGNB exposes neither UENodeIDs nor ConnectedUEs on this ' ...
             'release, so the scheduler RNTI cannot be resolved. Run ' ...
             'phase5_SchedulerDiag to list the available properties and ' ...
             'update this function rather than reverting to an offset.']);

        k = find(g.UENodeIDs == UEs(u).ID);
        assert(~isempty(k), 'phase5_ResolveRNTI:ueNotAtAnchor', ...
            ['UE %d (node %d) is absent from the connection table of ' ...
             'its anchor gNB %d. The pipeline''s anchor bookkeeping and ' ...
             'the toolbox disagree, which would silently empty this ' ...
             'UE''s CQI, MCS and traffic columns.'], u, UEs(u).ID, anchorIdx(u));
        assert(isscalar(k), 'phase5_ResolveRNTI:duplicateEntry', ...
            ['UE %d (node %d) appears %d times in the connection table ' ...
             'of gNB %d.'], u, UEs(u).ID, numel(k), anchorIdx(u));

        map.sched(u) = g.ConnectedUEs(k);
    end

    % two UEs on one anchor must not share a scheduler RNTI
    for g = unique(anchorIdx)
        sel = anchorIdx == g;
        r = map.sched(sel);
        assert(numel(unique(r)) == numel(r), ...
            'phase5_ResolveRNTI:collidingRNTI', ...
            ['Two or more UEs anchored at gNB %d resolve to the same ' ...
             'scheduler RNTI (%s). Their scheduler observables would be ' ...
             'merged.'], g, mat2str(r));
    end

    if printMap
        fprintf(['RNTI map [%s seed %d]  %d gNB, %d UE  (SRS offset %+d, ' ...
            'verified in flight)\n'], cfg.scenario, cfg.seed, ...
            numel(gNBs), numUE, cfg.rntiOffset);
        fprintf('  %-4s %-6s %-7s %-8s %-11s %s\n', ...
            'UE', 'node', 'class', 'anchor', 'schedRNTI', 'srsRNTI');
        for u = 1:numUE
            if cfg.ueIsAerial(u), cls = 'aerial'; else, cls = 'terr'; end
            fprintf('  %-4d %-6d %-7s %-8d %-11d %d\n', u, UEs(u).ID, ...
                cls, anchorIdx(u), map.sched(u), map.srs(u));
        end
    end
end
