function schema = phase5FeatureSchema()
%phase5FeatureSchema The Phase 5 dataset column set.
%
%   SCHEMA = phase5FeatureSchema() returns the ordered column list for the
%   labelled feature CSV, built by calling phase4FeatureSchema and appending,
%   so the earlier schemas stay exact prefixes.
%
%   Every column is an operator-side measurement: per-cell uplink SRS SINR,
%   handover and serving-cell history, scheduler CSI reports and grants, HARQ
%   outcomes, timing advance and MAC byte counters. Nothing uses UE position,
%   velocity, altitude or the LOS state.
%
%   Do not add a LOS flag: it is not observable and is near-collinear with
%   the aerial label. Its observable consequences are covered by
%   cqiSubbandSpread_mean, servSINR_autocorr1, servSINR_fadeRate_dBperS and
%   rankOne_frac.
%
%   Appended columns, all per UE per window.
%
%   Rank and CSI structure:
%     ri_mean                 mean reported DL rank indicator
%     ri_var                  variance of the reported rank indicator
%     rankOne_frac            fraction of reports with RI == 1
%     cqiSubbandSpread_mean   mean across-subband CQI standard deviation
%     ulMcsCtx_mean           mean SRS-derived UL MCS estimate, gNB-side and
%                             so not UE-falsifiable
%     ulMcsCtx_var            variance of the same
%
%   Resource consumption:
%     prbDL_mean, prbUL_mean  mean granted resource blocks per grant
%     prbDL_sum,  prbUL_sum   total granted resource blocks in the window
%     grantRateDL_perS        DL grants per second
%     grantRateUL_perS        UL grants per second
%     layers_mean             mean granted spatial layers
%     spectralEff_bpsPerPRB   (UL+DL bits) / (UL+DL granted PRBs)
%
%   Reliability, a residual-BLER estimate:
%     retxRateDL              DL retransmission grants / all DL grants
%     retxRateUL              UL retransmission grants / all UL grants
%     retxRate                combined; NaN when no grants at all
%
%   Timing advance, NaN throughout when the release does not surface it:
%     ta_mean, ta_var         moments of the timing advance
%     ta_trend_perS           least-squares slope of TA vs time
%     ta_range                max minus min within the window
%
%   Serving-SINR dynamics:
%     servSINR_trend_perS     least-squares slope of serving SINR (dB/s)
%     servSINR_range_dB       max minus min
%     servSINR_iqr_dB         interquartile range
%     servSINR_min_dB         minimum in the window
%     servSINR_max_dB         maximum in the window
%     servSINR_autocorr1      lag-1 autocorrelation of the scan series
%     servSINR_fadeRate_dBperS  mean |dSINR|/dt between consecutive scans
%
%   Cell geometry:
%     servMinusBestNbr_mean_dB  mean (serving - best neighbour) margin
%     servMinusBestNbr_min_dB   worst margin in the window
%     nbrSINR_max_var_dB2       variance of the best-neighbour SINR
%     sinrSpread_var_dB2        variance of the across-cell SINR spread
%     sinrSpread_trend_perS     slope of the across-cell SINR spread
%     numAboveThr_var           variance of the visible-cell count
%     numAboveThr_max           maximum visible-cell count
%     numAboveThr_trend_perS    slope of the visible-cell count
%     nbrWithin3dB_mean         mean cells within 3 dB of the serving cell
%     nbrWithin6dB_mean         same at 6 dB
%     top3NbrSpread_mean_dB     mean spread across the three strongest
%
%   Serving-cell history:
%     distinctServCells_win     distinct serving cells in the window
%     servCellEntropy           Shannon entropy (bits) of the scan fractions
%     pingPongCount_win         A -> B -> A serving-cell reversals
%     hoRate_perS               handovers per second
%     timeSinceHO_mean_s        mean of the logged time-since-handover
%     timeSinceHO_min_s         minimum of the same
%
%   Traffic, per direction:
%     ulThr_bps, dlThr_bps      per-direction mean throughput
%     trafficIdle_frac          fraction of intervals with zero bytes
%     ulVol_trend_Bps           least-squares slope of the UL byte rate
%     dlVol_trend_Bps           least-squares slope of the DL byte rate
%
%   A NaN means the window held no observation of that kind, never zero.

    schema = [phase4FeatureSchema(), { ...
        ... % rank and CSI structure
        'ri_mean', ...
        'ri_var', ...
        'rankOne_frac', ...
        'cqiSubbandSpread_mean', ...
        'ulMcsCtx_mean', ...
        'ulMcsCtx_var', ...
        ... % resource consumption
        'prbDL_mean', ...
        'prbUL_mean', ...
        'prbDL_sum', ...
        'prbUL_sum', ...
        'grantRateDL_perS', ...
        'grantRateUL_perS', ...
        'layers_mean', ...
        'spectralEff_bpsPerPRB', ...
        ... % reliability
        'retxRateDL', ...
        'retxRateUL', ...
        'retxRate', ...
        ... % timing advance
        'ta_mean', ...
        'ta_var', ...
        'ta_trend_perS', ...
        'ta_range', ...
        ... % serving SINR dynamics
        'servSINR_trend_perS', ...
        'servSINR_range_dB', ...
        'servSINR_iqr_dB', ...
        'servSINR_min_dB', ...
        'servSINR_max_dB', ...
        'servSINR_autocorr1', ...
        'servSINR_fadeRate_dBperS', ...
        ... % cell geometry
        'servMinusBestNbr_mean_dB', ...
        'servMinusBestNbr_min_dB', ...
        'nbrSINR_max_var_dB2', ...
        'sinrSpread_var_dB2', ...
        'sinrSpread_trend_perS', ...
        'numAboveThr_var', ...
        'numAboveThr_max', ...
        'numAboveThr_trend_perS', ...
        'nbrWithin3dB_mean', ...
        'nbrWithin6dB_mean', ...
        'top3NbrSpread_mean_dB', ...
        ... % serving-cell history
        'distinctServCells_win', ...
        'servCellEntropy', ...
        'pingPongCount_win', ...
        'hoRate_perS', ...
        'timeSinceHO_mean_s', ...
        'timeSinceHO_min_s', ...
        ... % traffic
        'ulThr_bps', ...
        'dlThr_bps', ...
        'trafficIdle_frac', ...
        'ulVol_trend_Bps', ...
        'dlVol_trend_Bps'}];
end
