function phase5b_ValidateFeatures()
%phase5b_ValidateFeatures Unit test of the extraction, the power tap and the CSV writer.
%
%   Runs in seconds, no simulation needed. Drives the REAL
%   phase5b_ExtractWindowedFeatures and phase5b_WriteFeatureCSV with synthetic
%   logs whose windowed features are known in closed form.
%
%   Every Phase 5 check is retained so the append-only contract is exercised,
%   and the Phase 5b power block is checked the same way.
%
%   Checks:
%     1. Column set equals the locked Phase 5b schema, with the Phase 5,
%        Phase 4 and Phase 3 schemas as exact prefixes.
%     2. Labels carried through.
%     3. CQI block: linear ramp gives the expected slope; constant CQI gives
%        zero variance and slope.
%     4. MCS block: known grant streams give the expected moments.
%     5. Traffic block: steady counters give the expected volumes, throughput,
%        asymmetry sign, near-zero burstiness and zero idle fraction; a bursty
%        counter gives high burstiness.
%     6. Rank/CSI block: constant RI 1 gives rankOne_frac 1; the subband
%        spread is carried through.
%     7. Resource and reliability: PRB moments, grant rates, and a
%        retransmission pattern of known fraction.
%     8. Timing advance: a linear TA ramp gives the expected slope, and the
%        range is exact.
%     9. SINR dynamics: a sinusoidal series of unit amplitude gives a range of
%        2, the correct min/max, and a lag-1 autocorrelation close to 1.
%    10. Cell geometry: hand-built per-cell SINR snapshots give exact
%        near-equal-cell counts and top-3 spreads.
%    11. Serving-cell history: a single serving cell gives one distinct cell,
%        zero entropy and zero ping-pongs.
%    12. Settle gating: rows before cfg.settleTime never influence a window.
%    13. The CSV regenerates byte-for-byte on rewrite.
%    14. Narrow scheduler logs degrade to NaN rather than erroring.
%    15. RSRP, RSSI and RSRQ: constants, a ramp and a sinusoid recover exactly.
%    16. phase5b_PowerTap.derive satisfies its defining identities and its
%        high-SINR limit.
%    17. The tap returns NaN for a stale entry rather than a wrong packet.
%    18. A manager with no power columns leaves the block NaN, not zero.

    here = fileparts(mfilename('fullpath'));
    addpath(fullfile(here, 'core', 'functions'));
    tol = 1e-6;
    fprintf('=== phase5b_ValidateFeatures ===\n');

    %% Synthetic scenario: 2 UEs, 15 s of 10 ms scans, settle 0.5 s
    fakeNames = {'time','ueID','label_is_aerial','servingGNB','servingSINR', ...
        'numVisible','maxNeighbourSINR','meanNeighbourSINR','sinrSpread', ...
        'handoverCount','timeSinceLastHO','servingRSRP','servingRSSI','servingRSRQ'};
    t = (0.1:0.01:15)';
    gnbs = struct('ID', {1, 2, 3});
    one = ones(size(t));

    % Per-cell SINR snapshots. Serving cell is gNB 1 throughout.
    %   UE 4: neighbours at -2 dB and -8 dB  -> within3 = 1, within6 = 1,
    %                                            top3 spread = 6
    %   UE 5: neighbours at -1 dB and -2 dB  -> within3 = 2, within6 = 2,
    %                                            top3 spread = 1
    mkSINR = @(serv, o1, o2) [t, serv, serv + o1, serv + o2];

    % Power columns, chosen for exact closed forms:
    %   UE 4  constant RSRP and RSSI, RSRQ on a linear ramp
    %   UE 5  sinusoidal RSRP of unit amplitude, constant RSSI and RSRQ
    rsrqSlope = 0.5;                      % dB/s
    rsrp4 = -90*one;    rssi4 = -70*one;  rsrq4 = -12 + rsrqSlope*(t - t(1));
    rsrp5 = -100 + sin(t); rssi5 = -65*one; rsrq5 = -15*one;

    mk = @(id, lbl, base, o1, o2, rp, rs, rq) struct( ...
        'featureLog', [t, id*one, lbl*one, one, base + sin(t), 3*one, ...
            base - 3 + cos(t), base - 5 + 0*t, 8 + 0*t, cumsum(t > 7), ...
            max(t - 7, t), rp, rs, rq], ...
        'featureNames', {fakeNames}, ...
        'ueLabel', string(tern(lbl, "aerial", "terrestrial")), ...
        'handoverTimes', tern(lbl, 7.5, zeros(1,0)), ...
        'sinrLog', mkSINR(base + sin(t), o1, o2), ...
        'gNBs', gnbs, ...
        'UE', struct('ID', id, 'Name', "UE-" + id));

    managers = {mk(4, 0, 20, -2, -8, rsrp4, rssi4, rsrq4), ...
                mk(5, 1, 25, -1, -2, rsrp5, rssi5, rsrq5)};

    cfg = struct('scenario', "UMa", 'seed', 42, 'windowLen', 10, ...
        'windowStride', 1, 'settleTime', 0.5, 'rntiOffset', -2, ...
        'outputDir', tempname);

    %% Scheduler context log (9 columns)
    % [t, rnti, cqi, ri, ulMcsCtx, cqiSubbandSpread, TA, bufDL, bufUL]
    rnti = [4 5] + cfg.rntiOffset;
    ts = (0.5:0.05:15)';                  % 20 Hz context snapshots
    n = numel(ts);
    taSlope = 3;                          % TA units per second, UE 5
    ctx = [ ...
        [ts, rnti(1)*ones(n,1), 10*ones(n,1), ones(n,1), 9*ones(n,1), ...
         0.5*ones(n,1), 40*ones(n,1), 100*ones(n,1), 200*ones(n,1)]; ...
        [ts, rnti(2)*ones(n,1), 6 + (ts - ts(1))*(6/(ts(end)-ts(1))), ...
         ones(n,1), 14*ones(n,1), ...
         2.0*ones(n,1), 40 + taSlope*(ts - ts(1)), 300*ones(n,1), 400*ones(n,1)] ];

    %% Grant log (8 columns)
    % [t, rnti, dir, mcs, numRBs, isRetx, numLayers, harqID]
    % Every 4th grant is a retransmission -> retx fraction exactly 0.25.
    tg = (0.5:0.02:15)'; m2 = numel(tg);
    alt = repmat([10; 14], ceil(m2/2), 1); alt = alt(1:m2);
    retx = double(mod((0:m2-1)', 4) == 0);
    z = zeros(m2,1); o = ones(m2,1);
    grants = [ ...
        [tg, rnti(1)*o, z, 12*o, 5*o, retx, 2*o, mod((0:m2-1)',16)]; ...
        [tg, rnti(1)*o, o,  7*o, 5*o, z,    2*o, mod((0:m2-1)',16)]; ...
        [tg, rnti(2)*o, z, alt,  5*o, retx, 2*o, mod((0:m2-1)',16)]; ...
        [tg, rnti(2)*o, o, 20*o, 5*o, z,    2*o, mod((0:m2-1)',16)] ];

    sched = struct('ctx', {{ctx}}, 'grants', {{grants}}, ...
        'anchorIdx', [1 1], 'rnti', rnti);

    %% Traffic: steady streams, opposite asymmetry
    tt = (0:0.1:15)'; ns = numel(tt);
    trafficLogs = { ...
        [tt, (0:ns-1)'*300,  (0:ns-1)'*3000, (0:ns-1)'*300,  (0:ns-1)'*3000], ...
        [tt, (0:ns-1)'*5000, (0:ns-1)'*125,  (0:ns-1)'*5000, (0:ns-1)'*125] };

    %% Run the real extraction
    T = phase5b_ExtractWindowedFeatures(managers, cfg, sched, trafficLogs);
    r1 = T(T.ueID == 4, :); r2 = T(T.ueID == 5, :);

    %% 1. Schema and prefix contract
    check(isequal(T.Properties.VariableNames, phase5bFeatureSchema()), ...
        'output columns equal the locked Phase 5b schema');
    p5 = phase5FeatureSchema();
    check(isequal(T.Properties.VariableNames(1:numel(p5)), p5), ...
        'Phase 5 schema is an exact prefix (append-only contract)');
    p4 = phase4FeatureSchema();
    check(isequal(T.Properties.VariableNames(1:numel(p4)), p4), ...
        'Phase 4 schema is an exact prefix (append-only contract)');
    p3 = phase3FeatureSchema();
    check(isequal(T.Properties.VariableNames(1:numel(p3)), p3), ...
        'Phase 3 schema is an exact prefix (append-only contract)');

    %% 2. Labels
    check(all(T.label(T.ueID == 5) == 1) && all(T.label(T.ueID == 4) == 0), ...
        'labels carried through');

    %% 3. CQI block
    check(all(abs(r1.cqi_mean - 10) < tol) && all(r1.cqi_var < tol) && ...
          all(abs(r1.cqi_trend_perS) < 1e-3), ...
        'constant CQI: mean 10, zero variance, zero trend');
    slope = 6 / (ts(end) - ts(1));
    check(all(abs(r2.cqi_trend_perS - slope) < 1e-3), ...
        sprintf('CQI ramp: recovered slope %.4f CQI/s', slope));

    %% 4. MCS block
    check(all(abs(r1.mcsDL_mean - 12) < tol) && all(r1.mcsDL_var < tol) && ...
          all(abs(r1.mcsUL_mean - 7) < tol), ...
        'constant MCS moments (DL 12, UL 7)');
    check(all(abs(r2.mcsDL_mean - 12) < 0.05) && ...
          all(abs(r2.mcsDL_var - 4) < 0.1) && ...
          all(abs(r2.mcsUL_mean - 20) < tol), ...
        'alternating DL MCS 10/14: mean 12, var 4; UL 20');

    %% 5. Traffic block
    check(all(abs(r1.dlVol_bytes - 100*3000) < 3000) && ...
          all(abs(r1.ulVol_bytes - 100*300) < 300), ...
        'terrestrial volumes: about 300 kB DL, 30 kB UL per window');
    check(all(r1.dlulAsym > 0.8) && all(r2.dlulAsym < -0.8), ...
        'asymmetry signs: terrestrial DL-heavy (+), aerial UL-heavy (-)');
    check(all(r1.trafficBurstiness_cv < 0.05) && ...
          all(r2.trafficBurstiness_cv < 0.05), ...
        'steady streams: near-zero burstiness');
    check(all(abs(r1.ulThr_bps - r1.ulVol_bytes*8/10) < tol) && ...
          all(abs(r1.dlThr_bps - r1.dlVol_bytes*8/10) < tol), ...
        'per-direction throughput equals volume*8/windowLen');
    check(all(r1.trafficIdle_frac < tol), ...
        'steady stream: zero idle fraction');
    check(all(abs(r1.ulVol_trend_Bps) < 1e-3), ...
        'steady stream: zero UL rate trend');

    % Bursty counter: 10x the bytes in every 10th interval, zero otherwise
    burst = zeros(ns,1); burst(1:10:end) = 30000; burstCum = cumsum(burst);
    tl2 = trafficLogs; tl2{1}(:,4:5) = [burstCum, burstCum];
    Tb = phase5b_ExtractWindowedFeatures(managers, cfg, sched, tl2);
    check(all(Tb.trafficBurstiness_cv(Tb.ueID == 4) > 1), ...
        'bursty stream: coefficient of variation well above 1');
    check(all(Tb.trafficIdle_frac(Tb.ueID == 4) > 0.8), ...
        'bursty stream: idle fraction above 0.8');

    %% 6. Rank / CSI structure
    check(all(abs(r1.ri_mean - 1) < tol) && all(r1.ri_var < tol) && ...
          all(abs(r1.rankOne_frac - 1) < tol), ...
        'constant RI 1: mean 1, zero variance, rankOne_frac 1');
    check(all(abs(r1.cqiSubbandSpread_mean - 0.5) < tol) && ...
          all(abs(r2.cqiSubbandSpread_mean - 2.0) < tol), ...
        'subband CQI spread carried through (0.5 and 2.0)');
    check(all(abs(r1.ulMcsCtx_mean - 9) < tol) && ...
          all(abs(r2.ulMcsCtx_mean - 14) < tol), ...
        'SRS-derived UL MCS estimate carried through (9 and 14)');

    %% 7. Resource and reliability
    check(all(abs(r1.prbDL_mean - 5) < tol) && all(abs(r1.prbUL_mean - 5) < tol), ...
        'PRB moments: constant 5 RBs per grant');
    check(all(abs(r1.grantRateDL_perS - 50) < 0.5), ...
        'DL grant rate about 50/s at a 20 ms grant spacing');
    check(all(abs(r1.layers_mean - 2) < tol), 'granted layers constant 2');
    check(all(abs(r1.retxRateDL - 0.25) < 0.01) && all(r1.retxRateUL < tol), ...
        'retransmission fraction: 0.25 DL, 0 UL');
    check(all(abs(r1.retxRate - 0.125) < 0.01), ...
        'combined retransmission fraction 0.125 over both directions');
    check(all(isfinite(r1.spectralEff_bpsPerPRB) & ...
              r1.spectralEff_bpsPerPRB > 0), ...
        'spectral efficiency finite and positive');

    %% 8. Timing advance
    check(all(abs(r1.ta_mean - 40) < tol) && all(r1.ta_var < tol) && ...
          all(abs(r1.ta_range) < tol), ...
        'constant TA: mean 40, zero variance, zero range');
    check(all(abs(r2.ta_trend_perS - taSlope) < 1e-3), ...
        sprintf('TA ramp: recovered slope %.3f units/s', taSlope));
    check(all(abs(r2.ta_range - taSlope*10) < 0.2), ...
        'TA range equals slope times window length');

    %% 9. Serving-SINR dynamics
    % serv = base + sin(t); a 10 s window spans more than one period, so the
    % range is 2 and the extremes are base -/+ 1.
    check(all(abs(r1.servSINR_range_dB - 2) < 0.01), ...
        'sinusoidal SINR: range exactly 2 dB');
    check(all(abs(r1.servSINR_min_dB - 19) < 0.01) && ...
          all(abs(r1.servSINR_max_dB - 21) < 0.01), ...
        'sinusoidal SINR: min 19 dB, max 21 dB');
    check(all(r1.servSINR_autocorr1 > 0.99), ...
        'smooth series at 10 ms sampling: lag-1 autocorrelation above 0.99');
    check(all(r1.servSINR_fadeRate_dBperS > 0 & ...
              r1.servSINR_fadeRate_dBperS < 1), ...
        'fade rate positive and below 1 dB/s for a unit-amplitude sinusoid');
    check(all(isfinite(r1.servSINR_iqr_dB) & r1.servSINR_iqr_dB > 0), ...
        'interquartile range finite and positive');

    %% 10. Cell geometry
    check(all(abs(r1.nbrWithin3dB_mean - 1) < tol) && ...
          all(abs(r1.nbrWithin6dB_mean - 1) < tol), ...
        'UE 4 hears exactly one cell within 3 dB and within 6 dB');
    check(all(abs(r2.nbrWithin3dB_mean - 2) < tol) && ...
          all(abs(r2.nbrWithin6dB_mean - 2) < tol), ...
        'UE 5 hears exactly two cells within 3 dB and within 6 dB');
    check(all(abs(r1.top3NbrSpread_mean_dB - 6) < tol) && ...
          all(abs(r2.top3NbrSpread_mean_dB - 1) < tol), ...
        'top-3 neighbour spread exact (6 dB and 1 dB)');
    % margin = serv - maxN = 3 + sin(t) - cos(t). A 10 s window is not an
    % exact multiple of the period, so the residual is bounded by
    % 2*sqrt(2)/10 = 0.283; the tolerance is that bound, not a guess.
    check(all(abs(r1.servMinusBestNbr_mean_dB - 3) < 0.29), ...
        'serving-minus-best-neighbour margin averages 3 dB');

    %% 11. Serving-cell history
    check(all(r1.distinctServCells_win == 1) && all(r1.servCellEntropy < tol), ...
        'single serving cell: one distinct cell, zero entropy');
    check(all(r1.pingPongCount_win == 0), 'no ping-pong with a single cell');
    check(all(abs(r2.hoRate_perS - r2.hoCount_win/10) < tol), ...
        'handover rate equals count over window length');

    %% 12. Settle gating
    check(all(T.winStart_s >= cfg.settleTime - tol), ...
        'no window starts before the settle cut-off');

    %% 13. Byte-identical CSV
    f1 = phase5b_WriteFeatureCSV(T, cfg); b1 = fileread(f1);
    f2 = phase5b_WriteFeatureCSV(T, cfg); b2 = fileread(f2);
    check(isequal(b1, b2), 'CSV byte-identical on rewrite');

    %% 14. Narrow (Phase 4 width) logs degrade to NaN, not to an error
    schedNarrow = struct('ctx', {{ctx(:, 1:5)}}, ...
        'grants', {{grants(:, 1:5)}}, 'anchorIdx', [1 1], 'rnti', rnti);
    Tn = phase5b_ExtractWindowedFeatures(managers, cfg, schedNarrow, trafficLogs);
    check(isequal(Tn.Properties.VariableNames, phase5bFeatureSchema()), ...
        'narrow logs still produce the full Phase 5b column set');
    check(all(isnan(Tn.cqiSubbandSpread_mean)) && all(isnan(Tn.ta_mean)) && ...
          all(isnan(Tn.retxRateDL)) && all(isnan(Tn.layers_mean)), ...
        'columns with no source data come back NaN, not zero');
    check(all(abs(Tn.cqi_mean - T.cqi_mean) < tol | ...
              (isnan(Tn.cqi_mean) & isnan(T.cqi_mean))), ...
        'Phase 4 columns unaffected by the log width');

    %% 15. RSRP, RSSI and RSRQ
    check(all(abs(r1.rsrp_mean_dBm + 90) < tol) && all(r1.rsrp_var_dB2 < tol) && ...
          all(abs(r1.rsrp_min_dBm + 90) < tol) && ...
          all(abs(r1.rsrp_max_dBm + 90) < tol) && ...
          all(abs(r1.rsrp_trend_dBperS) < 1e-3), ...
        'constant RSRP: mean -90 dBm, zero variance, zero range, zero trend');
    check(all(abs(r1.rssi_mean_dBm + 70) < tol) && all(r1.rssi_var_dB2 < tol), ...
        'constant RSSI: mean -70 dBm, zero variance');
    check(all(abs(r1.rsrq_trend_dBperS - rsrqSlope) < 1e-3), ...
        sprintf('RSRQ ramp: recovered slope %.3f dB/s', rsrqSlope));
    check(all(abs(r1.rsrq_max_dB - r1.rsrq_min_dB - rsrqSlope*10) < 0.02), ...
        'RSRQ ramp: max minus min equals slope times window length');
    check(all(abs(r2.rsrp_min_dBm + 101) < 0.01) && ...
          all(abs(r2.rsrp_max_dBm + 99) < 0.01), ...
        'sinusoidal RSRP: min -101 dBm, max -99 dBm');
    check(all(abs(r2.rsrq_mean_dB + 15) < tol) && all(r2.rsrq_var_dB2 < tol), ...
        'constant RSRQ: mean -15 dB, zero variance');

    %% 16. Power derivation
    numRB = 51;                               % 20 MHz at 30 kHz SCS
    pRx = -80; sinrDB = 20;
    [rp, rs, rq] = phase5b_PowerTap.derive(pRx, sinrDB, numRB);
    check(abs(rp - (pRx - 10*log10(12*numRB))) < tol, ...
        'RSRP is the wideband power spread over 12 REs per resource block');
    pIN = pRx - sinrDB;
    check(abs(rs - 10*log10(10.^(pRx/10) + 10.^(pIN/10))) < tol, ...
        'RSSI is signal plus the interference-and-noise term implied by SINR');
    check(rs > pRx && rs < pRx + 0.05, ...
        'RSSI exceeds the signal alone but only slightly at 20 dB SINR');
    check(abs(rq - (10*log10(numRB) + rp - rs)) < tol, ...
        'RSRQ satisfies its defining identity');
    [~, ~, rqHigh] = phase5b_PowerTap.derive(-80, 60, numRB);
    check(abs(rqHigh + 10*log10(12)) < 1e-4, ...
        'RSRQ tends to -10*log10(12) as SINR grows, the interference-free limit');
    [rpN, rsN, rqN] = phase5b_PowerTap.derive(NaN, 20, numRB);
    check(isnan(rpN) && isnan(rsN) && isnan(rqN), ...
        'a missing power reading gives NaN, never a value');

    %% 17. Tap freshness
    tap = phase5b_PowerTap([1 2], [4 5], 11);
    tap.record(1, 4, 1.0, -80);
    check(abs(tap.read(1, 4, 1.0005) - (-80 + 11)) < tol, ...
        'a fresh entry reads back with the receive gain applied');
    check(isnan(tap.read(1, 4, 1.02)), ...
        'an entry older than one subframe reads NaN, not the wrong packet');
    check(isnan(tap.read(2, 4, 1.0005)), ...
        'a pair with no entry reads NaN');
    check(isnan(tap.read(1, 4, 0.999)), ...
        'a read before the entry was written reads NaN');

    %% 18. A manager with no power columns
    noPwr = managers;
    for k = 1:numel(noPwr)
        noPwr{k}.featureNames = fakeNames(1:11);
        noPwr{k}.featureLog   = noPwr{k}.featureLog(:, 1:11);
    end
    Tp = phase5b_ExtractWindowedFeatures(noPwr, cfg, sched, trafficLogs);
    check(isequal(Tp.Properties.VariableNames, phase5bFeatureSchema()), ...
        'a run with no power tap still produces the full column set');
    check(all(isnan(Tp.rsrp_mean_dBm)) && all(isnan(Tp.rssi_mean_dBm)) && ...
          all(isnan(Tp.rsrq_mean_dB)) && all(isnan(Tp.rsrp_trend_dBperS)), ...
        'the power block comes back NaN throughout, not zero');

    fprintf('All Phase 5b feature-extraction checks passed.\n');
end

%% local helpers
function check(cond, what)
    if cond
        fprintf('PASS  %s\n', what);
    else
        error('phase5b_ValidateFeatures:fail', 'FAIL: %s', what);
    end
end

function out = tern(cond, a, b)
    if cond, out = a; else, out = b; end
end
