function schema = phase3FeatureSchema()
%phase3FeatureSchema The locked Phase 3 dataset column set (D3.1).
%
%   SCHEMA = phase3FeatureSchema() returns the ordered list of column
%   names for the labelled feature CSV. This list is FINAL for all later
%   phases: training, evaluation, and the interim oral dataset all consume
%   it. Any change here invalidates every previously generated CSV, so the
%   single source of truth lives in this one function and both
%   extractWindowedFeatures and writeFeatureCSV assert against it.
%
%   The scenario column is part of the schema from the start so that the
%   UMa, RMa, and UMi forks all emit identical column sets and their CSVs
%   can be concatenated without rework.

    schema = { ...
        'scenario', ...              % UMa | RMa | UMi
        'seed', ...                  % run RNG seed
        'ueID', ...                  % simulator node ID
        'label', ...                 % 0 terrestrial, 1 aerial (ground truth)
        'winStart_s', ...
        'winEnd_s', ...
        'servSINR_mean_dB', ...
        'servSINR_var_dB2', ...
        'nbrSINR_max_mean_dB', ...
        'nbrSINR_mean_mean_dB', ...
        'sinrSpread_mean_dB', ...
        'numAboveThr_mean', ...
        'hoCount_win', ...
        'meanInterHO_s'};
end
