%% Phase 8 D8.4 - False positive audit under every condition
%  Reads:  results/scores_ue.csv, results/scores_window.csv, results/thresholds_frozen.csv
%          Phase 7 feature CSVs, for the terrestrial invariance diagnostic only
%  Writes: results/fpr_audit.csv, results/fpr_audit_terrestrial_invariance.csv, figures/fpr_audit.png
%
%  The purpose is to establish that the recall changes reported in D8.2 and D8.3 are
%  attributable to the evasion policy and not to the operating point having moved. If the
%  false positive rate drifts between conditions then the detector is not being held at
%  the same place on its own curve and the recall comparison is not like for like.
%
%  Two things bound what this can show.
%
%  The per-UE rate can only move in whole terrestrial UE-runs, so its resolution is one
%  over the number of them. With the hold-out as generated that step is close to the
%  nominal one per cent target itself, which means "the operating point held" can be
%  established only to within about one step and the table states the step size next to
%  every rate rather than leaving it to be inferred.
%
%  The frozen thresholds were derived on full-length development runs. Truncating a UE-run
%  shortens the sequence its mean posterior averages over, which widens the null
%  distribution of that statistic and moves the achieved rate away from nominal. That
%  movement is a property of the observation length. It is why the honest condition is
%  audited at both lengths, and why the truncated honest row rather than the nominal one
%  per cent is the reference every evasive condition is read against.
%
%  This is the only stage after p8_score that opens a raw feature CSV. The invariance
%  diagnostic is a question about the features themselves, not about any score, so it
%  cannot be answered from the score tables.

%% Settings
clear; clc;
C = p8_config();
V = p8_util();

Uue = readtable(C.f.scoresUE,     'TextType', 'string');
Uwn = readtable(C.f.scoresWindow, 'TextType', 'string');
Thr = readtable(fullfile(C.resultsDir, 'thresholds_frozen.csv'), 'TextType', 'string');

rows = {};
fprintf('===== D8.4 false positive audit =====\n\n');

for m = 1:numel(C.modelNames)
    mdl = string(C.modelNames{m});

    for c = 1:numel(C.conditions)
        cond = string(C.conditions{c});

        for level = ["Window", "PerUE"]
            lengths = "Truncated";
            if cond == "honest", lengths = ["Full", "Truncated"]; end

            for len = lengths
                if level == "Window"
                    S = Uwn(Uwn.Model == mdl & Uwn.Condition == cond, :);
                    if len == "Truncated", S = S(S.WinIdx <= C.nWin, :); end
                    score = S.Score;
                else
                    S = Uue(Uue.Model == mdl & Uue.Condition == cond, :);
                    if len == "Full", score = S.ScoreFull; else, score = S.ScoreTrunc; end
                end
                isPos  = S.Label == 1;
                runKey = S.RunKey;

                for q = 1:numel(C.opLabels)
                    t = Thr.Threshold(Thr.Model == mdl & Thr.Level == level & ...
                                      Thr.OperatingPoint == string(C.opLabels{q}));
                    pt = V.metricsAt(score, isPos, t);

                    fprStat = @(idx) V.fprAt(score(idx), isPos(idx), t);
                    [~, lo, hi] = V.clusterBoot(runKey, fprStat, C.nBoot, C.bootSeed, C.ciLevel);

                    nominal = Thr.NominalFPR(Thr.Model == mdl & Thr.Level == level & ...
                                             Thr.OperatingPoint == string(C.opLabels{q}));

                    rows{end+1} = {mdl, cond, string(level), string(len), ...
                        string(C.opLabels{q}), nominal, t, ...
                        pt.nNeg, 1 / pt.nNeg, pt.FP, pt.FPR, lo, hi, ...
                        pt.nPos, pt.TPR, m == C.primaryIdx}; %#ok<SAGROW>
                end
            end
        end
    end
    fprintf('%-22s done\n', mdl);
end

T = cell2table(vertcat(rows{:}), 'VariableNames', ...
    {'Model', 'Condition', 'Level', 'Length', 'OperatingPoint', 'NominalFPR', 'Threshold', ...
     'NegativeUnits', 'FPRGranularity', 'FalsePositives', 'FPR', 'FPR_lo', 'FPR_hi', ...
     'PositiveUnits', 'TPR', 'IsPrimary'});
writetable(T, fullfile(C.resultsDir, 'fpr_audit.csv'));

%% Terrestrial invariance diagnostic
%  The evasive runs were generated by changing the aerial UE's behaviour, so a first
%  reading would expect the terrestrial UEs to be untouched and their false positive rate
%  to be identical by construction. If that were so the audit above would be a tautology.
%
%  It is not, and the diagnostic establishes which of two explanations applies. If the
%  terrestrial features move, the aerial UE's altered altitude and traffic have changed
%  interference and scheduling for everyone in the cell, which is a physical coupling and
%  a legitimate secondary finding: an evading drone perturbs the cell it hides in. If the
%  terrestrial features move a great deal and unsystematically, the more likely
%  explanation is that changing the aerial policy shifted the random stream and the
%  terrestrial UEs are simply different draws, in which case the seed pairing that D8.2
%  rests on is weaker than it appears and the write-up must say so.
tol   = 1e-9;
invRows = {};
feats = C.frozenFeatureNames;

honestFiles = dir(fullfile(C.dataDir, 'honest', 'features_*.csv'));
for c = 2:numel(C.conditions)
    cond = string(C.conditions{c});
    nMatched = 0;  nIdentical = 0;
    diffCount = zeros(numel(feats), 1);
    diffMed   = nan(numel(feats), 1);
    accum     = cell(numel(feats), 1);

    for k = 1:numel(honestFiles)
        hf = fullfile(honestFiles(k).folder, honestFiles(k).name);
        ef = fullfile(C.condPaths{c}, honestFiles(k).name);
        if ~isfile(ef), continue; end

        Hh = readtable(hf);  Ee = readtable(ef);
        Hh = Hh(Hh.label == 0, :);  Ee = Ee(Ee.label == 0, :);

        kH = strcat(string(Hh.ueID), '_', string(round(Hh.winStart_s, 4)));
        kE = strcat(string(Ee.ueID), '_', string(round(Ee.winStart_s, 4)));
        [tf, loc] = ismember(kH, kE);
        Hh = Hh(tf, :);  Ee = Ee(loc(tf), :);
        if isempty(Hh), continue; end

        A = Hh{:, feats};  B = Ee{:, feats};
        d = abs(A - B);
        d(isnan(A) & isnan(B)) = 0;

        nMatched   = nMatched + height(Hh);
        nIdentical = nIdentical + sum(all(d <= tol | isnan(d), 2));
        diffCount  = diffCount + sum(d > tol, 1)';
        for j = 1:numel(feats)
            v = d(d(:, j) > tol, j);
            if ~isempty(v), accum{j} = [accum{j}; v]; end
        end
    end

    for j = 1:numel(feats)
        if ~isempty(accum{j}), diffMed(j) = median(accum{j}); end
    end

    for j = 1:numel(feats)
        invRows{end+1} = {cond, string(feats{j}), nMatched, diffCount(j), ...
            diffCount(j) / max(nMatched, 1), diffMed(j)}; %#ok<SAGROW>
    end

    fprintf(['\n%-18s %d matched terrestrial rows, %d (%.1f%%) identical across all %d ' ...
             'predictors\n'], cond, nMatched, nIdentical, ...
             100 * nIdentical / max(nMatched, 1), numel(feats));
    [~, ord] = sort(diffCount, 'descend');
    for j = ord(1:min(4, numel(ord)))'
        if diffCount(j) == 0, break; end
        fprintf('    %-26s %5.1f%% of rows differ, median change %.4g\n', ...
            feats{j}, 100 * diffCount(j) / max(nMatched, 1), diffMed(j));
    end
end

Tinv = cell2table(vertcat(invRows{:}), 'VariableNames', ...
    {'Condition', 'Feature', 'MatchedTerrestrialRows', 'RowsDiffering', ...
     'FractionDiffering', 'MedianAbsoluteChange'});
writetable(Tinv, fullfile(C.resultsDir, 'fpr_audit_terrestrial_invariance.csv'));

%% Figure: measured false positive rate by condition
fig = figure('Position', [100 100 820 400], 'Color', 'w');
tl  = tiledlayout(fig, 1, 2, 'Padding', 'compact', 'TileSpacing', 'compact');
opLab = string(C.opLabels{C.opIdx});
pal   = V.palette();

for level = ["Window", "PerUE"]
    ax = nexttile(tl); hold(ax, 'on');
    S = T(T.IsPrimary & T.Level == level & T.OperatingPoint == opLab & ...
          T.Length == "Truncated", :);
    [~, ord] = ismember(S.Condition, string(C.conditions));
    [~, srt] = sort(ord);
    S = S(srt, :);
    x = 1:height(S);
    for i = x
        bar(ax, i, S.FPR(i), 0.6, 'FaceColor', pal(min(i, size(pal, 1)), :), ...
            'FaceAlpha', 0.75, 'EdgeColor', 'none');
    end
    errorbar(ax, x, S.FPR, S.FPR - S.FPR_lo, S.FPR_hi - S.FPR, 'k', ...
        'LineStyle', 'none', 'LineWidth', 1);
    yline(ax, S.NominalFPR(1), '--', 'Color', [0.7 0.2 0.2], 'LineWidth', 1, ...
        'Label', 'nominal', 'LabelHorizontalAlignment', 'left', 'FontSize', 8);
    if level == "PerUE"
        yline(ax, S.FPRGranularity(1), ':', 'Color', [0.4 0.4 0.4], ...
            'Label', 'one UE-run', 'LabelHorizontalAlignment', 'left', 'FontSize', 8);
    end
    xticks(ax, x); xticklabels(ax, S.Condition); xtickangle(ax, 20);
    ylabel(ax, 'Measured false positive rate');
    title(ax, sprintf('%s level', level));
    V.styleAxes(ax);
end
title(tl, sprintf('D8.4 operating point under every condition, %s, %s, first %d windows', ...
    C.primaryName, opLab, C.nWin));
V.saveFig(fig, fullfile(C.figureDir, 'fpr_audit.png'));
close(fig);

%% Report
fprintf('\n----- primary model, %s, per-UE, %s, truncated -----\n', C.primaryName, opLab);
P = T(T.IsPrimary & T.Level == "PerUE" & T.OperatingPoint == opLab & T.Length == "Truncated", :);
ref = P.FPR(P.Condition == "honest");
for i = 1:height(P)
    fprintf('%-18s FPR %s   %d of %d terrestrial UE-runs   %+.2f steps from honest\n', ...
        P.Condition(i), V.fmtCI(P.FPR(i), P.FPR_lo(i), P.FPR_hi(i), 4), ...
        P.FalsePositives(i), P.NegativeUnits(i), ...
        (P.FPR(i) - ref) / P.FPRGranularity(i));
end
fprintf(['\nA drift of less than one step is not evidence that the operating point moved. ' ...
         'The\nrecall changes in D8.2 and D8.3 are attributable to the evasion policy only ' ...
         'to the\nextent that these rates agree.\n']);
fprintf('\nWrote results/fpr_audit.csv, fpr_audit_terrestrial_invariance.csv, figures/fpr_audit.png\n');


%% ============================================================================
%% Report outputs
%% ============================================================================
RPT     = report_util();
figDir  = C.figureDir;
keyFile = fullfile(C.resultsDir, 'phase8_key_results.txt');
RPT.ensureDir(figDir);

%% T8.7 Did the operating point hold under every condition
fprTxt  = strings(height(P), 1);
stepTxt = strings(height(P), 1);
for i = 1:height(P)
    fprTxt(i)  = RPT.fmtCI(P.FPR(i), P.FPR_lo(i), P.FPR_hi(i), 4);
    stepTxt(i) = string(sprintf('%+.2f', (P.FPR(i) - ref) / P.FPRGranularity(i)));
end
T87 = table(P.Condition, P.Threshold, P.NegativeUnits, P.FalsePositives, fprTxt, ...
    stepTxt, P.TPR, ...
    'VariableNames', {'Condition', 'Frozen_threshold', 'Terrestrial_UE_runs', ...
                      'False_positives', 'FPR_95pct_CI', 'Steps_from_honest', 'Recall'});

RPT.tableFigure(T87, fullfile(figDir, 'T8_7_fpr_audit.png'), struct( ...
    'Title', sprintf('T8.7  D8.4 false positive audit, %s, per-UE, %s, first %d windows', ...
                     C.primaryName, opLab, C.nWin), ...
    'Highlight', P.Condition == "honest", ...
    'Note', ["";sprintf('The per-UE rate can only move in whole UE-runs, so one step is 1/%d = %.3f%%.', ...
                     P.NegativeUnits(1), 100 * P.FPRGranularity(1)); ...
             "A drift of less than one step is not evidence that the operating point moved."; ...
             "The recall changes in D8.2 and D8.3 are attributable to the evasion policy only to the extent"; ...
             "that these rates agree."]));

%% T8.8 Are the terrestrial UEs really untouched
%  If they were identical by construction the audit above would be a tautology. They
%  are not, and which explanation applies matters: physical coupling is a finding,
%  RNG-stream divergence weakens the seed pairing that D8.2 rests on.
invRowsShow = cell(0, 1);
for c = 2:numel(C.conditions)
    cond = string(C.conditions{c});
    Q = Tinv(Tinv.Condition == cond, :);
    Q = sortrows(Q, 'RowsDiffering', 'descend');
    nShow = min(3, height(Q));
    for j = 1:nShow
        invRowsShow{end + 1} = {char(cond), char(Q.Feature(j)), Q.MatchedTerrestrialRows(j), ...
            Q.RowsDiffering(j), 100 * Q.FractionDiffering(j), Q.MedianAbsoluteChange(j)}; %#ok<SAGROW>
    end
end
T88 = cell2table(vertcat(invRowsShow{:}), 'VariableNames', ...
    {'Condition', 'Predictor', 'Matched_terrestrial_rows', 'Rows_differing', ...
     'Pct_differing', 'Median_abs_change'});

RPT.tableFigure(T88, fullfile(figDir, 'T8_8_terrestrial_invariance.png'), struct( ...
    'Title', 'T8.8  D8.4 do the terrestrial UEs move when the aerial policy changes', ...
    'Note', ["";"Three most-affected predictors per condition, matched row by row on UE and window start."; ...
             "Movement here means the aerial UE's altered altitude and traffic changed interference and"; ...
             "scheduling for everyone in the cell, which is a physical coupling and a secondary finding."; ...
             "Large and unsystematic movement would instead mean the random stream diverged, which would"; ...
             "weaken the seed pairing D8.2 rests on. The write-up must say which reading applies."]));

%% Key results
lines = strings(0, 1);
lines(end + 1) = sprintf('Primary model          : %s, per-UE, %s, truncated to %d windows', ...
                         C.primaryName, opLab, C.nWin);
lines(end + 1) = sprintf('FPR resolution         : 1/%d = %.3f%% per step', ...
                         P.NegativeUnits(1), 100 * P.FPRGranularity(1));
for i = 1:height(P)
    lines(end + 1) = sprintf('%-18s FPR %s, %d of %d terrestrial UE-runs, %+.2f steps from honest', ...
        P.Condition(i), RPT.fmtCI(P.FPR(i), P.FPR_lo(i), P.FPR_hi(i), 4), ...
        P.FalsePositives(i), P.NegativeUnits(i), (P.FPR(i) - ref) / P.FPRGranularity(i));
end
RPT.logSection(keyFile, 'D8.4  False positive audit', lines);
RPT.logTable(keyFile, T87, 8);
RPT.logSection(keyFile, 'D8.4  Terrestrial invariance diagnostic', "");
RPT.logTable(keyFile, T88, 12);
