%% Phase 8 - Score every hold-out condition with every frozen pipeline
%  Reads:  data/honest/*.csv and data/evasive/*/*.csv, Phase 8's own copy of the
%          hold-out runs generated by Phase 7
%          models/frozen_*.mat
%  Writes: results/scores_window.csv, results/scores_ue.csv,
%          results/thresholds_frozen.csv, results/provenance.csv
%
%  This is the only Phase 8 script that reads a raw feature CSV or opens a frozen model.
%  Every deliverable stage after it reads the two score tables and nothing else.
%
%  There is one scoring script rather than one per condition. Four near-identical scripts
%  would be four places for a preprocessing or truncation mistake to hide, and the point
%  of a frozen pipeline is that every condition is treated identically, which is easier to
%  demonstrate when the code doing the treating is the same code. Conditions are
%  discovered from the folder tree, so a third evasion action appearing in the final
%  dataset is picked up without any script being edited.
%
%  Nothing is fitted here. Imputation medians, scaling constants, the decision rule and
%  both thresholds are read from the frozen files through score_pipeline, which is the
%  sanctioned entry point. If any constant ever has to be computed from hold-out data,
%  the freeze has failed and the result is not a hold-out result.

%% Settings
clear; clc;
C = p8_config();
U = phase6_util();

fprintf('===== Phase 8 scoring =====\n');
fprintf('Frozen on   : %s\n', string(C.freezeDate));
fprintf('Dev seeds   : %s\n', U.rangeText(C.devSeeds));
fprintf('Hold-out    : %s\n', U.rangeText(C.holdoutSeeds));
fprintf('Conditions  : %s\n', strjoin(C.conditions, ', '));
fprintf('Models      : %s (primary: %s)\n', strjoin(C.modelNames', ', '), C.primaryName);
fprintf('Truncation  : first %d windows per UE-run (shortest observed: %d)\n\n', ...
    C.nWin, C.minWinObserved);

winRows = {};
ueRows  = {};
provRows = {};

%% Score each condition
for c = 1:numel(C.conditions)
    cond  = C.conditions{c};
    % Hold-out files only. The seed filter lives in p8_config and is applied once, so
    % this stage must not glob the directory itself: the copied data folder still holds
    % the development runs and a second, subtly different filter is how one of them
    % would eventually reach a result.
    files = C.condFiles{c};

    T = table();
    for k = 1:numel(files)
        T = [T; readtable(files{k})]; %#ok<AGROW>
    end

    runKey = strcat(string(T.scenario), '_', string(T.seed));
    ueKey  = strcat(runKey, '_', string(T.ueID));
    winStart = double(T.winStart_s);
    isPos    = double(T.label) == C.posLabel;

    % --- window index within a UE-run, so downstream stages can truncate consistently ---
    %  Computed from the time order rather than from the row order, because a pooled table
    %  is only in time order by construction and that is not a guarantee worth relying on.
    [ueList, ~, g] = unique(ueKey, 'stable');
    winIdx = zeros(height(T), 1);
    nWinPerUE = zeros(numel(ueList), 1);
    for i = 1:numel(ueList)
        m = find(g == i);
        [~, byTime] = sort(winStart(m));
        winIdx(m(byTime)) = 1:numel(m);
        nWinPerUE(i) = numel(m);
    end

    assert(all(nWinPerUE >= C.nWin), 'p8_score:shortUE', ...
        ['Condition "%s" contains %d UE-run(s) with fewer than the %d windows the ' ...
         'truncation asks for.'], cond, sum(nWinPerUE < C.nWin), C.nWin);
    if numel(unique(nWinPerUE)) > 1
        fprintf(['Note: condition "%s" has uneven window counts per UE-run (%d to %d). ' ...
                 'Truncation to %d makes them comparable.\n'], ...
                cond, min(nWinPerUE), max(nWinPerUE), C.nWin);
    end

    % --- per-UE bookkeeping, taken once and reused for every model ---
    ueFirst  = arrayfun(@(i) find(g == i, 1), (1:numel(ueList))');
    ueScen   = string(T.scenario(ueFirst));
    ueSeed   = double(T.seed(ueFirst));
    ueID     = string(T.ueID(ueFirst));
    ueRun    = runKey(ueFirst);
    ueIsPos  = arrayfun(@(i) any(isPos(g == i)), (1:numel(ueList))');

    for m = 1:numel(C.modelFiles)
        mf = char(C.modelFiles{m});

        outFull  = score_pipeline(mf, T, ueKey, winStart);
        outTrunc = score_pipeline(mf, T, ueKey, winStart, 'MaxWindows', C.nWin);

        % --- window level ---
        n = height(T);
        winRows{end+1} = table( ...
            repmat(string(cond), n, 1), string(T.scenario), double(T.seed), string(T.ueID), ...
            runKey, ueKey, double(T.label), winStart, winIdx, ...
            repmat(string(C.modelNames{m}), n, 1), outFull.window.Score, ...
            'VariableNames', {'Condition', 'Scenario', 'Seed', 'UEID', 'RunKey', 'UEKey', ...
                              'Label', 'WinStart_s', 'WinIdx', 'Model', 'Score'}); %#ok<SAGROW>

        % --- per-UE level, full length and truncated ---
        %  perUEScore returns UEs in first-appearance order, which is the order ueList was
        %  built in, but the alignment is asserted rather than assumed because a silent
        %  mismatch here would attach every score to the wrong UE.
        assert(isequal(string(outFull.perUE.UE), ueList) && ...
               isequal(string(outTrunc.perUE.UE), ueList), 'p8_score:ueOrder', ...
            'The per-UE score table is not in the expected UE order for condition "%s".', cond);

        nU = numel(ueList);
        ueRows{end+1} = table( ...
            repmat(string(cond), nU, 1), ueScen, ueSeed, ueID, ueRun, ueList, double(ueIsPos), ...
            repmat(string(C.modelNames{m}), nU, 1), repmat(string(outFull.info.rule), nU, 1), ...
            outFull.perUE.nWindows, outFull.perUE.Score, ...
            outTrunc.perUE.nWindows, outTrunc.perUE.Score, ...
            'VariableNames', {'Condition', 'Scenario', 'Seed', 'UEID', 'RunKey', 'UEKey', ...
                              'Label', 'Model', 'Rule', ...
                              'nWinFull', 'ScoreFull', 'nWinTrunc', 'ScoreTrunc'}); %#ok<SAGROW>
    end

    fprintf('%-18s %3d runs, %5d rows, %4d UE-runs (%d aerial), %d windows per UE-run\n', ...
        cond, numel(unique(runKey)), height(T), numel(ueList), sum(ueIsPos), ...
        median(nWinPerUE));

    provRows{end+1} = {string(cond), numel(unique(runKey)), height(T), numel(ueList), ...
        sum(ueIsPos), sum(~ueIsPos), min(nWinPerUE), max(nWinPerUE)}; %#ok<SAGROW>
end

%% Write the score tables
Wtab = vertcat(winRows{:});
Utab = vertcat(ueRows{:});
writetable(Wtab, C.f.scoresWindow);
writetable(Utab, C.f.scoresUE);

%% Write the frozen thresholds as their own small table
%  Kept separate rather than repeated on every score row, and read by every stage that
%  applies an operating point, so no stage can quietly use a different number.
thrRows = {};
for m = 1:numel(C.modelFiles)
    S = load(C.modelFiles{m}, 'pipeline');
    p = S.pipeline;
    for q = 1:numel(p.nominalFPR)
        thrRows{end+1} = {string(p.name), string(p.key), 'Window', C.opLabels{q}, ...
            p.nominalFPR(q), p.windowThreshold(q), p.isPrimary}; %#ok<SAGROW>
        thrRows{end+1} = {string(p.name), string(p.key), 'PerUE', C.opLabels{q}, ...
            p.nominalFPR(q), p.ueThreshold(q), p.isPrimary}; %#ok<SAGROW>
    end
end
Thr = cell2table(vertcat(thrRows{:}), 'VariableNames', ...
    {'Model', 'Key', 'Level', 'OperatingPoint', 'NominalFPR', 'Threshold', 'IsPrimary'});
writetable(Thr, fullfile(C.resultsDir, 'thresholds_frozen.csv'));

%% Provenance
%  What was evaluated, with what, on what, and when. This is the block an examiner probes
%  first, and it costs nothing to produce it as output rather than as a claim in prose.
Prov = cell2table(vertcat(provRows{:}), 'VariableNames', ...
    {'Condition', 'Runs', 'Rows', 'UERuns', 'AerialUERuns', 'TerrestrialUERuns', ...
     'MinWindowsPerUE', 'MaxWindowsPerUE'});
Prov.FreezeDate  = repmat(string(C.freezeDate), height(Prov), 1);
Prov.DevSeeds    = repmat(string(mat2str(C.devSeeds)), height(Prov), 1);
Prov.HoldoutSeeds = repmat(string(mat2str(C.holdoutSeeds)), height(Prov), 1);
Prov.nWinTruncation = repmat(C.nWin, height(Prov), 1);
Prov.nPredictors = repmat(numel(C.frozenFeatureNames), height(Prov), 1);
Prov.PrimaryModel = repmat(string(C.primaryName), height(Prov), 1);
writetable(Prov, C.f.provenance);

%% Report the granularity every later stage is bounded by
nNegUE = Prov.TerrestrialUERuns(strcmp(Prov.Condition, 'honest'));
nPosUE = Prov.AerialUERuns(strcmp(Prov.Condition, 'honest'));
fprintf('\n----- resolution of the hold-out -----\n');
fprintf('Aerial UE-runs      : %d. Detection moves one UE-run at a time.\n', nPosUE);
fprintf('Terrestrial UE-runs : %d. A nominal 1%% false positive target admits %d of them.\n', ...
    nNegUE, floor(0.01 * nNegUE));
fprintf(['Results in this phase are reported as counts of UE-runs. One aerial UE-run is\n' ...
         '%.1f points of recall and one terrestrial UE-run is %.3f points of false positive\n' ...
         'rate, so a percentage carries precision this sample has not earned.\n'], ...
    100 / nPosUE, 100 / nNegUE);

aerialPerRun = groupcounts(Utab(Utab.Label == 1 & Utab.Condition == "honest" & ...
                                Utab.Model == string(C.primaryName), :), 'RunKey');
if max(aerialPerRun.GroupCount) > 3 * min(aerialPerRun.GroupCount)
    warning('p8_score:unbalancedAerial', ...
        ['Aerial UE-runs are unevenly spread across runs (%d to %d per run). A run-level ' ...
         'bootstrap will be correspondingly lumpy, and seed-paired recall differences will ' ...
         'be coarse. This is a property of the dataset, not of the analysis, and should be ' ...
         'stated wherever a per-UE interval is quoted.'], ...
        min(aerialPerRun.GroupCount), max(aerialPerRun.GroupCount));
end

fprintf('\nWrote %s (%d rows)\n', C.f.scoresWindow, height(Wtab));
fprintf('Wrote %s (%d rows)\n', C.f.scoresUE, height(Utab));
fprintf('Wrote %s\n', C.f.provenance);
fprintf(['\nNext, in this order. Only p8_score reads a feature CSV, so the stages below can ' ...
         'be\nrerun individually while a table or a figure is being settled.\n' ...
         '  p8_holdout             D8.1, also the per-scenario breakdown\n' ...
         '  p8_evasion_individual  D8.2, every evasion condition against honest\n' ...
         '  p8_fpr_audit           D8.4\n' ...
         '  p8_base_rate           D8.5, needs p8_holdout\n' ...
         '  p8_frontier            D8.6\n' ...
         '  p8_latency             D8.7\n']);


%% ============================================================================
%% Report outputs
%  Presentation only. Everything below re-renders what the score tables already
%  contain, so a figure and a CSV can never disagree. The key-results file starts
%  here because p8_score is always the first Phase 8 stage to run.
%% ============================================================================
RPT     = report_util();
figDir  = C.figureDir;
keyFile = fullfile(C.resultsDir, 'phase8_key_results.txt');
RPT.ensureDir(figDir);
RPT.logNew(keyFile, 'PHASE 8 KEY RESULTS');

%% T8.1 What was evaluated, with what, on what
Tprov = table(Prov.Condition, Prov.Runs, Prov.Rows, Prov.UERuns, Prov.AerialUERuns, ...
    Prov.TerrestrialUERuns, Prov.MinWindowsPerUE, Prov.MaxWindowsPerUE, ...
    'VariableNames', {'Condition', 'Runs', 'Rows', 'UE_runs', 'Aerial_UE_runs', ...
                      'Terrestrial_UE_runs', 'Min_windows_per_UE', 'Max_windows_per_UE'});

RPT.tableFigure(Tprov, fullfile(figDir, 'T8_1_provenance.png'), struct( ...
    'Title', sprintf('T8.1  Hold-out provenance, seeds %d to %d', ...
                     min(C.holdoutSeeds), max(C.holdoutSeeds)), ...
    'Highlight', Tprov.Condition == "honest", ...
    'Note', ["";sprintf('Frozen %s on development seeds %s; the two sets are disjoint and the assertion is in p8_config.', ...
                     string(C.freezeDate), U.rangeText(C.devSeeds)); ...
             sprintf('Every UE-run is truncated to its first %d windows before any comparison between conditions.', C.nWin); ...
             sprintf('%d predictors, %d frozen pipelines, primary is %s.', ...
                     numel(C.frozenFeatureNames), numel(C.modelFiles), C.primaryName)]));

%% Key results
RPT.logSection(keyFile, 'Provenance', [""; ...
    sprintf('Frozen                 : %s', string(C.freezeDate)); ...
    sprintf('Development seeds      : %s', U.rangeText(C.devSeeds)); ...
    sprintf('Hold-out seeds         : %s', U.rangeText(C.holdoutSeeds)); ...
    sprintf('Conditions             : %s', strjoin(C.conditions, ', ')); ...
    sprintf('Models                 : %s', strjoin(C.modelNames', ', ')); ...
    sprintf('Primary model          : %s', C.primaryName); ...
    sprintf('Predictors             : %d', numel(C.frozenFeatureNames)); ...
    sprintf('Truncation             : first %d windows per UE-run (shortest observed %d)', ...
            C.nWin, C.minWinObserved); ...
    sprintf('Aerial UE-runs         : %d', nPosUE); ...
    sprintf('Terrestrial UE-runs    : %d, of which a 1%% target admits %d', ...
            nNegUE, floor(0.01 * nNegUE)); ...
    'Reporting unit         : counts of UE-runs, not rates']);
RPT.logTable(keyFile, Tprov, 8);
